server:
  port: 8761

eureka:
  instance:
  #    hostname: localhost
  # docker
  prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://${spring.cloud.client.ip-address}:${server.port}/eureka/