drop table user if exists ;
create table user(id bigint generated by default as identity ,username varchar(40),name varchar(20), age int(3), balance decimal(10,2), primary key (id));
insert into user(id,username,name,age,balance) values (1,'account1','name1',20, 181.00);
insert into user(id,username,name,age,balance) values (2,'account2','name2',21, 182.00);
insert into user(id,username,name,age,balance) values (3,'account3','name3',22, 183.00);
insert into user(id,username,name,age,balance) values (4,'account4','name4',23, 184.00);